### ISSUE TITLE
Integration into Mendix

### ISSUE THREAD

**Issue by Boris-Scharinger** [daniel-hauser/react-organizational-chart#18]
Hi Daniel - is there a chance to  get in touch with you for a potentially paid mini-project to integrate org chart into the Mendix low code environment? Thanks & regards, Boris

**Comment by syedaliammar** [comment]
Hi @Boris-Scharinger , let's connect.

**Comment by daniel-hauser** [comment]
@Boris-Scharinger Sorry for missing this, I assume this is not relevant anymore. 
Closing the issue
