### ISSUE TITLE
How to export react-organizational-chart in pdf or png/jpg

### ISSUE THREAD

**Issue by muhammadadnan371** [daniel-hauser/react-organizational-chart#21]
Hi, 

I am using react-organizational-chart in one of my project and it's working perfect. Now I want to export my chart in pdf or png/jpg format. I tried react-to-pdf but it only show one or two nodes of my chart. I want whole chart even there is horizontal scroll.

Please help help me to achieving this functionality.
Thanks!

**Comment by daniel-hauser** [comment]
You can try using https://github.com/niklasvh/html2canvas.
Ill appreciate if you comment on this thread if it worked for you
