### ISSUE TITLE
OnClick functionality does not work for Tree Nodes

### ISSUE THREAD

**Issue by adheesh24** [daniel-hauser/react-organizational-chart#39]
Is there a way to trigger an event when clicked on a Node?
I want to open a pop-up on click of the nodes. 

Any help would be appreciated.

**Comment by avishmonga** [comment]
you can add tree in a div and add onclick functionality on div only

**Comment by daniel-hauser** [comment]
The best way to do it is to handle the events in the component you pass as `label`.

```jsx
const ExampleTree = () => (
  <Tree label={<div>Root</div>}>
    <TreeNode label={<button onClick={() => console.log('clicked')}>Child 1</button>} />
  </Tree>
);
```
