### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by pou4a** [daniel-hauser/react-organizational-chart#40]
I trying to use react organizational chart but I keep getting this error:

ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
r.key
file:///Users/pouya/Documents/Sites/automation_majma_new/node_modules/react-organizational-chart/dist/index.js (1:17845)
<unknown>
file:///Users/pouya/Documents/Sites/automation_majma_new/node_modules/react-organizational-chart/dist/index.js (1:19892)
Object.<anonymous>
file:///Users/pouya/Documents/Sites/automation_majma_new/node_modules/react-organizational-chart/dist/index.js (1:20947)
Module._compile
node:internal/modules/cjs/loader (1099:14)
Object.Module._extensions..js
node:internal/modules/cjs/loader (1153:10)
Module.load
node:internal/modules/cjs/loader (975:32)
Function.Module._load
node:internal/modules/cjs/loader (822:12)
Module.require
node:internal/modules/cjs/loader (999:19)
require
node:internal/modules/cjs/helpers (102:18)
Object.react-organizational-chart
file:///Users/pouya/Documents/Sites/automation_majma_new/.next/server/pages/organizationalChart.js (461:18)

what is the problem guys?

**Comment by daniel-hauser** [comment]
Looks like you are using [Next.js](https://nextjs.org/), if that's the case it might be related to https://github.com/emotion-js/emotion/issues/2801
